/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankmain;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author piyus
 */
public class asignteach extends javax.swing.JFrame {

    /**
     * Creates new form asignteach
     */
    public asignteach() {
        initComponents();
        setLocationRelativeTo(null);
        jButton1.setVisible(false);
         t1.setVisible(false);
          t2.setVisible(false);
           t3.setVisible(false);
            t4.setVisible(false);
             t5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        sub2 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        r2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        sub3 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        r3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        sub1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        r1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        sub5 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        r5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        sub4 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        r4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(124, 85, 227));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("ASSIGN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, 190, 50));

        jPanel2.setBackground(new java.awt.Color(124, 85, 227));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "/ select /", "sem1", "sem2", "sem3", "sem4", "sem5", "sem6", "sem7", "sem8", " " }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 160, 30));

        jButton2.setText("GET SUBJECTS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 190, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 250, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 90));

        jPanel4.setBackground(new java.awt.Color(0, 109, 228));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sub2.setFont(new java.awt.Font("Joanna MT", 1, 24)); // NOI18N
        sub2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(sub2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 290, 50));
        jPanel4.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 280, 40));

        r2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        r2.setForeground(new java.awt.Color(255, 0, 0));
        jPanel4.add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 24, 110, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 170, 860, 80));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sub3.setFont(new java.awt.Font("Joanna MT", 1, 24)); // NOI18N
        sub3.setForeground(new java.awt.Color(0, 109, 228));
        jPanel5.add(sub3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 290, 50));
        jPanel5.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 280, 40));

        r3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        r3.setForeground(new java.awt.Color(255, 0, 0));
        jPanel5.add(r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 24, 110, 40));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 250, 860, 80));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sub1.setFont(new java.awt.Font("Joanna MT", 1, 24)); // NOI18N
        sub1.setForeground(new java.awt.Color(0, 109, 228));
        jPanel6.add(sub1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 290, 50));
        jPanel6.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 280, 40));

        r1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        r1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel6.add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 24, 110, 40));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 90, 860, 80));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sub5.setFont(new java.awt.Font("Joanna MT", 1, 24)); // NOI18N
        sub5.setForeground(new java.awt.Color(0, 109, 228));
        jPanel7.add(sub5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 290, 50));
        jPanel7.add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 280, 40));

        r5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        r5.setForeground(new java.awt.Color(255, 0, 0));
        jPanel7.add(r5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 24, 110, 40));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 410, 860, 80));

        jPanel8.setBackground(new java.awt.Color(0, 109, 228));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sub4.setFont(new java.awt.Font("Joanna MT", 1, 24)); // NOI18N
        sub4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.add(sub4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 290, 50));
        jPanel8.add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 280, 40));

        r4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        r4.setForeground(new java.awt.Color(255, 0, 0));
        jPanel8.add(r4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 24, 110, 40));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 330, 860, 80));

        jPanel3.setBackground(new java.awt.Color(124, 85, 227));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sem1", "sem2", "sem3", "sem4", "sem5", "sem6", "sem7", "sem8", " " }));
        jPanel3.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 160, 30));

        jButton3.setText("GET SUBJECTS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 190, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sem=(String) jComboBox1.getSelectedItem();
        if(sem.equals("sem1"))
        {
            String s1=sub1.getText();
            String s2=sub2.getText();
            String s3=sub3.getText();
            String s4=sub4.getText();
            String s5=sub5.getText(); 
            
            String m1=t1.getText();
            String m2=t2.getText();
            String m3=t3.getText();
            String m4=t4.getText();
            String m5=t5.getText();
            if(m1.equals(""))
            {
                r1.setText("REQUIRED");
            }
            else if(m2.equals(""))
            {
                r2.setText("REQUIRED");
            }
            else if(m3.equals(""))
            {
                r3.setText("REQUIRED");
            }
            else if(m4.equals(""))
            {
                r4.setText("REQUIRED");
            }
            else if(m5.equals(""))
            {
                r5.setText("REQUIRED");
            }
            else
            {
                r1.setText("");
                r2.setText("");
                r3.setText("");
                r4.setText("");
                r5.setText("");
                
                
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
                Connection ncon=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/bank","root","");
                Statement stmt=ncon.createStatement();
           /*   //  String st1="insert into staffsem1 values('"+s1+"' , '"+m1+"')";
                 String st2="insert into staffsem1 values('"+s2+"' , '"+m2+"')";
                  String st3="insert into staffsem1 values('"+s3+"' , '"+m3+"')";
                   String st4="insert into staffsem1 values('"+s4+"' , '"+m4+"')";
                    String st5="insert into staffsem1 values('"+s5+"' , '"+m5+"')";
                     //String st= "update "+semes1+" set address='"+addr+"' WHERE rollno='"+roll1+"'";*/ 
              String st1="update staffsem1 set teachname='"+m1+"' WHERE subname='"+s1+"'";
               String st2="update staffsem1 set teachname='"+m2+"' WHERE subname='"+s2+"'";
                String st3="update staffsem1 set teachname='"+m3+"' WHERE subname='"+s3+"'";
                 String st4="update staffsem1 set teachname='"+m4+"' WHERE subname='"+s4+"'";
                  String st5="update staffsem1 set teachname='"+m5+"' WHERE subname='"+s5+"'";
              
                stmt.executeUpdate(st1);
                stmt.executeUpdate(st2);
                stmt.executeUpdate(st3);
                stmt.executeUpdate(st4);
                stmt.executeUpdate(st5);
                 JOptionPane.showMessageDialog(this,"data inserted");
                
                
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(this,ex);
            
            
            
            
        }
        }
        }
        else if(sem.equals("sem2"))
        {
            String s1=sub1.getText();
            String s2=sub2.getText();
            String s3=sub3.getText();
            String s4=sub4.getText();
            String s5=sub5.getText();
            String m1=t1.getText();
        String m2=t2.getText();
        String m3=t3.getText();
        String m4=t4.getText();
        String m5=t5.getText();
        
        if(m1.equals(""))
            {
                r1.setText("REQUIRED");
            }
            else if(m2.equals(""))
            {
                r2.setText("REQUIRED");
            }
            else if(m3.equals(""))
            {
                r3.setText("REQUIRED");
            }
            else if(m4.equals(""))
            {
                r4.setText("REQUIRED");
            }
            else if(m5.equals(""))
            {
                r5.setText("REQUIRED");
            }
            else{
                 r1.setText("");
                r2.setText("");
                r3.setText("");
                r4.setText("");
                r5.setText("");
            
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
                Connection ncon=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/bank","root","");
                Statement stmt=ncon.createStatement();
                /*String st1="insert into staffsem2 values('"+s1+"' , '"+m1+"')";
                 String st2="insert into staffsem2 values('"+s2+"' , '"+m2+"')";
                  String st3="insert into staffsem2 values('"+s3+"' , '"+m3+"')";
                   String st4="insert into staffsem2 values('"+s4+"' , '"+m4+"')";
                    String st5="insert into staffsem2 values('"+s5+"' , '"+m5+"')";
               // String x="insert into stable values('"+n+"','"+e+"','"+p+"')";*/
               String st1="update staffsem2 set teachname='"+m1+"' WHERE subname='"+s1+"'";
               String st2="update staffsem2 set teachname='"+m2+"' WHERE subname='"+s2+"'";
                String st3="update staffsem2 set teachname='"+m3+"' WHERE subname='"+s3+"'";
                 String st4="update staffsem2 set teachname='"+m4+"' WHERE subname='"+s4+"'";
                  String st5="update staffsem2 set teachname='"+m5+"' WHERE subname='"+s5+"'";
                stmt.executeUpdate(st1);
                stmt.executeUpdate(st2);
                stmt.executeUpdate(st3);
                stmt.executeUpdate(st4);
                stmt.executeUpdate(st5);
                 JOptionPane.showMessageDialog(this,"data inserted");
                
                
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(this,ex);
            
            
            
            
        }
            }
        }
        else if(sem.equals("sem3"))
        {
            String s1=sub1.getText();
            String s2=sub2.getText();
            String s3=sub3.getText();
            String s4=sub4.getText();
            String s5=sub5.getText(); 
            String m1=t1.getText();
        String m2=t2.getText();
        String m3=t3.getText();
        String m4=t4.getText();
        String m5=t5.getText();
        if(m1.equals(""))
            {
                r1.setText("REQUIRED");
            }
            else if(m2.equals(""))
            {
                r2.setText("REQUIRED");
            }
            else if(m3.equals(""))
            {
                r3.setText("REQUIRED");
            }
            else if(m4.equals(""))
            {
                r4.setText("REQUIRED");
            }
            else if(m5.equals(""))
            {
                r5.setText("REQUIRED");
            }
            else{
                 r1.setText("");
                r2.setText("");
                r3.setText("");
                r4.setText("");
                r5.setText("");
            
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
                Connection ncon=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/bank","root","");
                Statement stmt=ncon.createStatement();
               String st1="update staffsem3 set teachname='"+m1+"' WHERE subname='"+s1+"'";
               String st2="update staffsem3 set teachname='"+m2+"' WHERE subname='"+s2+"'";
                String st3="update staffsem3 set teachname='"+m3+"' WHERE subname='"+s3+"'";
                 String st4="update staffsem3 set teachname='"+m4+"' WHERE subname='"+s4+"'";
                  String st5="update staffsem3 set teachname='"+m5+"' WHERE subname='"+s5+"'";
               // String x="insert into stable values('"+n+"','"+e+"','"+p+"')";
                stmt.executeUpdate(st1);
                stmt.executeUpdate(st2);
                stmt.executeUpdate(st3);
                stmt.executeUpdate(st4);
                stmt.executeUpdate(st5);
                 JOptionPane.showMessageDialog(this,"data inserted");
                
                
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(this,ex);
            
            
            
            
        }
            
        }
        }
        else if(sem.equals("sem4"))
        {
            String s1=sub1.getText();
            String s2=sub2.getText();
            String s3=sub3.getText();
            String s4=sub4.getText();
            String s5=sub5.getText(); 
            String m1=t1.getText();
        String m2=t2.getText();
        String m3=t3.getText();
        String m4=t4.getText();
        String m5=t5.getText();
        if(m1.equals(""))
            {
                r1.setText("REQUIRED");
            }
         else if(m2.equals(""))
            {
                r2.setText("REQUIRED");
            }
            else if(m3.equals(""))
            {
                r3.setText("REQUIRED");
            }
            else if(m4.equals(""))
            {
                r4.setText("REQUIRED");
            }
            else if(m5.equals(""))
            {
                r5.setText("REQUIRED");
            }
            else{
                 r1.setText("");
                r2.setText("");
                r3.setText("");
                r4.setText("");
                r5.setText("");
            
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
                Connection ncon=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/bank","root","");
                Statement stmt=ncon.createStatement();
                 String st1="update staffsem4 set teachname='"+m1+"' WHERE subname='"+s1+"'";
               String st2="update staffsem4 set teachname='"+m2+"' WHERE subname='"+s2+"'";
                String st3="update staffsem4 set teachname='"+m3+"' WHERE subname='"+s3+"'";
                 String st4="update staffsem4 set teachname='"+m4+"' WHERE subname='"+s4+"'";
                  String st5="update staffsem4 set teachname='"+m5+"' WHERE subname='"+s5+"'";
               // String x="insert into stable values('"+n+"','"+e+"','"+p+"')";
                stmt.executeUpdate(st1);
                stmt.executeUpdate(st2);
                stmt.executeUpdate(st3);
                stmt.executeUpdate(st4);
                stmt.executeUpdate(st5);
                 JOptionPane.showMessageDialog(this,"data inserted");
                
                
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(this,ex);
            
            
            
            
        }
            }
        }
        else if(sem.equals("sem5"))
        {
             String s1=sub1.getText();
            String s2=sub2.getText();
            String s3=sub3.getText();
            String s4=sub4.getText();
            String s5=sub5.getText(); 
            String m1=t1.getText();
        String m2=t2.getText();
        String m3=t3.getText();
        String m4=t4.getText();
        String m5=t5.getText();
        if(m1.equals(""))
            {
                r1.setText("REQUIRED");
            }
            else if(m2.equals(""))
                
            {
                r1.setText("");
                r2.setText("REQUIRED");
            }
            else if(m3.equals(""))
            {
                r2.setText("");
                r3.setText("REQUIRED");
            }
            else if(m4.equals(""))
            {
                r3.setText("");
                r4.setText("REQUIRED");
            }
            else if(m5.equals(""))
            {
                r4.setText("");
                r5.setText("REQUIRED");
            }
            else{
            
                 r1.setText("");
                r2.setText("");
                r3.setText("");
                r4.setText("");
                r5.setText("");
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
                Connection ncon=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/bank","root","");
                Statement stmt=ncon.createStatement();
                  String st1="update staffsem5 set teachname='"+m1+"' WHERE subname='"+s1+"'";
               String st2="update staffsem5 set teachname='"+m2+"' WHERE subname='"+s2+"'";
                String st3="update staffsem5 set teachname='"+m3+"' WHERE subname='"+s3+"'";
                 String st4="update staffsem5 set teachname='"+m4+"' WHERE subname='"+s4+"'";
                  String st5="update staffsem5 set teachname='"+m5+"' WHERE subname='"+s5+"'";
               // String x="insert into stable values('"+n+"','"+e+"','"+p+"')";
                stmt.executeUpdate(st1);
                stmt.executeUpdate(st2);
                stmt.executeUpdate(st3);
                stmt.executeUpdate(st4);
                stmt.executeUpdate(st5);
                 JOptionPane.showMessageDialog(this,"data inserted");
                
                
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(this,ex);
            
            
            
            } 
        }
        }
        else if(sem.equals("sem6"))
        {
            String s1=sub1.getText();
            String s2=sub2.getText();
            String s3=sub3.getText();
            String s4=sub4.getText();
            String s5=sub5.getText();
            String m1=t1.getText();
        String m2=t2.getText();
        String m3=t3.getText();
        String m4=t4.getText();
        String m5=t5.getText();
        if(m1.equals(""))
            {
                r1.setText("REQUIRED");
            }
            else if(m2.equals(""))
                
            {
                r1.setText("");
                r2.setText("REQUIRED");
            }
            else if(m3.equals(""))
            {
                r2.setText("");
                r3.setText("REQUIRED");
            }
            else if(m4.equals(""))
            {
                r3.setText("");
                r4.setText("REQUIRED");
            }
            else if(m5.equals(""))
            {
                r4.setText("");
                r5.setText("REQUIRED");
            }
            else{
                 r1.setText("");
                r2.setText("");
                r3.setText("");
                r4.setText("");
                r5.setText("");
            
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
                Connection ncon=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/bank","root","");
                Statement stmt=ncon.createStatement();
                  String st1="update staffsem6 set teachname='"+m1+"' WHERE subname='"+s1+"'";
               String st2="update staffsem6 set teachname='"+m2+"' WHERE subname='"+s2+"'";
                String st3="update staffsem6 set teachname='"+m3+"' WHERE subname='"+s3+"'";
                 String st4="update staffsem6 set teachname='"+m4+"' WHERE subname='"+s4+"'";
                  String st5="update staffsem6 set teachname='"+m5+"' WHERE subname='"+s5+"'";
               // String x="insert into stable values('"+n+"','"+e+"','"+p+"')";
                stmt.executeUpdate(st1);
                stmt.executeUpdate(st2);
                stmt.executeUpdate(st3);
                stmt.executeUpdate(st4);
                stmt.executeUpdate(st5);
                 JOptionPane.showMessageDialog(this,"data inserted");
                
                
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(this,ex);
            
            
            
            
        }
            }
            
        }
        else if(sem.equals("sem7"))
        {
             String s1=sub1.getText();
            String s2=sub2.getText();
            String s3=sub3.getText();
            String s4=sub4.getText();
            String s5=sub5.getText(); 
            String m1=t1.getText();
        String m2=t2.getText();
        String m3=t3.getText();
        String m4=t4.getText();
        String m5=t5.getText();
         if(m1.equals(""))
            {
                r1.setText("REQUIRED");
            }
            else if(m2.equals(""))
                
            {
                r1.setText("");
                r2.setText("REQUIRED");
            }
            else if(m3.equals(""))
            {
                r2.setText("");
                r3.setText("REQUIRED");
            }
            else if(m4.equals(""))
            {
                r3.setText("");
                r4.setText("REQUIRED");
            }
            else if(m5.equals(""))
            {
                r4.setText("");
                r5.setText("REQUIRED");
            }
            else{
                 r1.setText("");
                r2.setText("");
                r3.setText("");
                r4.setText("");
                r5.setText("");
            
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
                Connection ncon=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/bank","root","");
                Statement stmt=ncon.createStatement();
                 String st1="update staffsem7 set teachname='"+m1+"' WHERE subname='"+s1+"'";
               String st2="update staffsem7 set teachname='"+m2+"' WHERE subname='"+s2+"'";
                String st3="update staffsem7 set teachname='"+m3+"' WHERE subname='"+s3+"'";
                 String st4="update staffsem7 set teachname='"+m4+"' WHERE subname='"+s4+"'";
                  String st5="update staffsem7 set teachname='"+m5+"' WHERE subname='"+s5+"'";
               // String x="insert into stable values('"+n+"','"+e+"','"+p+"')";
                stmt.executeUpdate(st1);
                stmt.executeUpdate(st2);
                stmt.executeUpdate(st3);
                stmt.executeUpdate(st4);
                stmt.executeUpdate(st5);
                 JOptionPane.showMessageDialog(this,"data updated");
                
                
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(this,ex);
            
            
            
            }
        }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String sem=(String) jComboBox1.getSelectedItem();
        
       
        
        
        String table=null;
        if(sem.equals("sem1"))
        {
            jButton1.setVisible(true);
            jLabel1.setText("");
            sub1.setText("Maths 1");
            sub2.setText("Ed");
            sub3.setText("Eme");
            sub4.setText("Chem");
            sub5.setText("Fcpit");
            t1.setVisible(true);
            t2.setVisible(true);
            t3.setVisible(true);
            t4.setVisible(true);
            t5.setVisible(true);
            
            table="staffsem1";
            
            t1.setText("");
            t2.setText("");
            t3.setText("");
            t4.setText("");
            t5.setText("");
            
            
        }
      else if(sem.equals("sem2"))
        {
            jButton1.setVisible(true);
            jLabel1.setText("");
            sub1.setText("M2 ");
            sub2.setText("COMP. SCI");
            sub3.setText("PHY");
            sub4.setText("BEEE");
            sub5.setText("HUMAN VALUES");
             t2.setVisible(true);
            t1.setVisible(true);
            t3.setVisible(true);
            t4.setVisible(true);
            t5.setVisible(true);
            t2.setText("");
            t1.setText("");
            t3.setText("");
            t4.setText("");
            t5.setText("");
            table="staffsem2";
            
            
            
            
            
        }
        else if(sem.equals("sem3"))
        {
            jButton1.setVisible(true);
            jLabel1.setText("");
            sub5.setText("DESC Maths ");
            sub1.setText("DATA STRUCTURE");
            sub3.setText("CA");
            sub4.setText("OOPS");
            sub2.setText("DCID");
            t2.setVisible(true);
            t1.setVisible(true);
            t3.setVisible(true);
            t4.setVisible(true);
            t5.setVisible(true);
            t2.setText("");
            t1.setText("");
            t3.setText("");
            t4.setText("");
            t5.setText("");
            
            table="staffsem3";
            
            
            
            
            
        }
         else if(sem.equals("sem4"))
        {
            jButton1.setVisible(true);
            jLabel1.setText("");
            sub5.setText("MATHS 3");
            sub1.setText("OS");
            sub3.setText("CN");
            sub4.setText("SP");
            sub2.setText("MP");
            t2.setVisible(true);
            t1.setVisible(true);
            t3.setVisible(true);
            t4.setVisible(true);
            t5.setVisible(true);
            t2.setText("");
            t1.setText("");
            t3.setText("");
            t4.setText("");
            t5.setText("");
            table="staffsem4";
            
            
            
            
            
        }
         else if(sem.equals("sem5"))
        {
            jButton1.setVisible(true);
            sub5.setText("DAA");
            sub1.setText("CG");
            sub3.setText("GN2");
            sub4.setText("DEN");
            sub2.setText("EVS");
            t2.setVisible(true);
            t1.setVisible(true);
            t3.setVisible(true);
            t4.setVisible(true);
            t5.setVisible(true);
            t2.setText("");
            t1.setText("");
            t3.setText("");
            t4.setText("");
            t5.setText("");
            table="staffsem5";
            
           
            
            
        }
         else if(sem.equals("sem6"))
        {
            jButton1.setVisible(true);
            jLabel1.setText("");
            sub5.setText("CPI");
            sub1.setText("IWT");
            sub3.setText("BIT");
            sub4.setText("VISUAL BASIC");
            sub2.setText("SC");
            t2.setVisible(true);
            t1.setVisible(true);
            t3.setVisible(true);
            t4.setVisible(true);
            t5.setVisible(true);
            t2.setText("");
            t1.setText("");
            t3.setText("");
            t4.setText("");
            t5.setText("");
            table="staffsem6";
            
            
            
            
        }
         else if(sem.equals("sem7"))
        {
            jButton1.setVisible(true);
            jLabel1.setText("");
            sub5.setText("ATM");
            sub1.setText("BE");
            sub3.setText("DSPM");
            sub4.setText("MATHS");
            sub2.setText("PHYSICS");
            t2.setVisible(true);
            t1.setVisible(true);
            t3.setVisible(true);
            t4.setVisible(true);
            t5.setVisible(true);
            t2.setText("");
            t1.setText("");
            t3.setText("");
            t4.setText("");
            t5.setText("");
            table="staffsem7";
            
           
            
            
            
        }
         else if(sem.equals("sem8"))
        {
            jButton1.setVisible(false);
            jLabel1.setText("");
            
            sub5.setText("Smes. 8 is for traning");
            sub1.setText("");
            sub3.setText("");
            sub4.setText("");
            sub2.setText("");
            t2.setText("");
            t1.setText("");
            t3.setText("");
            t4.setText("");
            t5.setText("");
            
            table="staffsem8";
            t2.setVisible(false);
            t1.setVisible(false);
            t3.setVisible(false);
            t4.setVisible(false);
            t5.setVisible(false);
        }
        else
         {
             jLabel1.setText("(KINDLY SELECT A SEMESTER)");
                // JOptionPane.showMessageDialog(this,"kindly select a categeory");
         }
         String a[]=new String[30];
        String b[]=new String[30];
        int i=0;
        try
        {
         Class.forName("com.mysql.jdbc.Driver");
           // Class.forName("com.mysql.jdbc.Driver");
            Connection logc=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/bank","root","");
            Statement stmt=logc.createStatement();
            String so="select * from "+table+"";
            ResultSet rs=stmt.executeQuery(so);
            
           
             while(rs.next())
            {
              // b[i]=(String) rs.getString(2);
               a[i]=(String) rs.getString(2);
               i++;  
            }
             t1.setText(a[0]);
              t2.setText(a[1]);
               t3.setText(a[2]);
                t4.setText(a[3]);
                 t5.setText(a[4]);
            
            
            
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
          /*try
            {
                Class.forName("com.mysql.jdbc.Driver");
                Connection ncon=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/bank","root","");
                Statement stmt=ncon.createStatement();
                String st="insert into staffsem1 values()";
               // String x="insert into stable values('"+n+"','"+e+"','"+p+"')";
                stmt.executeUpdate(st);
                 JOptionPane.showMessageDialog(this,"data inserted");
                
                
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(this,ex);
                
                
               
            }*/
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(asignteach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(asignteach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(asignteach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(asignteach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new asignteach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel r1;
    private javax.swing.JLabel r2;
    private javax.swing.JLabel r3;
    private javax.swing.JLabel r4;
    private javax.swing.JLabel r5;
    private javax.swing.JLabel sub1;
    private javax.swing.JLabel sub2;
    private javax.swing.JLabel sub3;
    private javax.swing.JLabel sub4;
    private javax.swing.JLabel sub5;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables
}
