/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankmain;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author piyus
 */
public class viewfeed extends javax.swing.JFrame {

    /**
     * Creates new form viewfeed
     */
    public viewfeed() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        t5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t1 = new javax.swing.JLabel();
        t4 = new javax.swing.JLabel();
        t3 = new javax.swing.JLabel();
        t2 = new javax.swing.JLabel();
        f1 = new javax.swing.JLabel();
        f2 = new javax.swing.JLabel();
        f3 = new javax.swing.JLabel();
        f4 = new javax.swing.JLabel();
        f5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(95, 210, 195));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sem1", "sem2", "sem3", "sem4", "sem5", "sem6", "sem7", " " }));

        jButton1.setText("VIEW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 341, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, -1));

        jPanel3.setBackground(new java.awt.Color(34, 45, 65));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FEEDBACK");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 160, 30));

        t5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 160, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TEACHER NAME");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 160, 30));

        t1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 160, 30));

        t4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 160, 30));

        t3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 160, 30));

        t2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 160, 30));

        f1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        f1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 160, 30));

        f2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        f2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(f2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 160, 30));

        f3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        f3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(f3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 160, 30));

        f4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        f4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(f4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 160, 30));

        f5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        f5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(f5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 160, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 830, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String a[]=new String[35];
        String b[]=new String[35];
        
        String table=null;
        String sem=(String)jComboBox1.getSelectedItem();
        if(sem.equals("sem1"))
        {
            table="staffsem1";
            
        }
        else if(sem.equals("sem2"))
        {
            table="staffsem2";
        }
         else if(sem.equals("sem3"))
        {
            table="staffsem3";
        }
         else if(sem.equals("sem4"))
        {
            table="staffsem4";
        }
         else if(sem.equals("sem5"))
        {
            table="staffsem5";
        }
         else if(sem.equals("sem6"))
        {
            table="staffsem6";
        }
         else if(sem.equals("sem7"))
        {
            table="staffsem7";
        }
        
        
        
         try
        {
         Class.forName("com.mysql.jdbc.Driver");
           // Class.forName("com.mysql.jdbc.Driver");
            Connection logc=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/bank","root","");
            Statement stmt=logc.createStatement();
            String so="select * from "+table+"";
            ResultSet rs=stmt.executeQuery(so);
            
           int i=0;
             while(rs.next())
            {
              // b[i]=(String) rs.getString(2);
               b[i]=(String) rs.getString(3);//feedback
               a[i]=(String) rs.getString(2);//teacher
               i++;  
            }
             t1.setText(a[0]);
              t2.setText(a[1]);
               t3.setText(a[2]);
                t4.setText(a[3]);
                 t5.setText(a[4]);
                 
                 f1.setText(b[0]);
                  f2.setText(b[1]);
                   f3.setText(b[2]);
                    f4.setText(b[3]);
                     f5.setText(b[4]);
            
            
            
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewfeed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewfeed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewfeed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewfeed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewfeed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel f1;
    private javax.swing.JLabel f2;
    private javax.swing.JLabel f3;
    private javax.swing.JLabel f4;
    private javax.swing.JLabel f5;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel t1;
    private javax.swing.JLabel t2;
    private javax.swing.JLabel t3;
    private javax.swing.JLabel t4;
    private javax.swing.JLabel t5;
    // End of variables declaration//GEN-END:variables
}
